apiVersion: v1
kind: ConfigMap
metadata:
  name: gpt-api-config
  labels:
    app: gpt-api
data:
  POSTGRES_DRIVER: postgresql
  POSTGRES_DB: smarthack
  POSTGRES_USER: smarthack
  POSTGRES_PASSWORD: pwd
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpt-api
  template:
    metadata:
      labels:
        app: gpt-api
    spec:
      containers:
        - name: gpt-api
          image: core.harbor.domain/library/gpt-api:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: gpt-api-secrets
            - configMapRef:
                name: gpt-api-config
---
apiVersion: v1
kind: Service
metadata:
  name: gpt-api
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30500
      protocol: TCP
  selector:
    app: gpt-api
