apiVersion: v1
kind: ConfigMap
metadata:
  name: veridion-api-config
  labels:
    app: veridion-api
data:
  PROCESSING_DOMAIN: http://gpt-api/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: veridion-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: veridion-api
  template:
    metadata:
      labels:
        app: veridion-api
    spec:
      containers:
        - name: veridion-api
          image: core.harbor.domain/library/veridion-api:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: veridion-api-secrets
            - configMapRef:
                name: veridion-api-config
---
apiVersion: v1
kind: Service
metadata:
  name: veridion-api
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30501
      protocol: TCP
  selector:
    app: veridion-api
